
theme: jekyll-theme-minimal
title: Peters Test
description: Tester beskrivelse
logo: /assets/img/logo.png
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
